[package]
name = "lightcurve-fiting"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_with = "3.15.0"
schemars = "0.9.0"
anyhow = "1.0.100"
serde_json = "1.0.145"