[project]
name = "lightcurve-fitting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alerce>=2.1.1",
    "matplotlib>=3.10.8",
    "requests>=2.32.5",
]
